# Generated by Django 4.1.2 on 2022-11-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_l_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='l_songs',
            old_name='idd',
            new_name='s_id',
        ),
    ]
