# Generated by Django 4.1.2 on 2022-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_idd_l_songs_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='l_songs',
            name='thumbnail',
            field=models.ImageField(default='/static/images/musiqal_logo.png', upload_to=''),
        ),
    ]
