# Generated by Django 4.1.2 on 2022-11-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_l_songs_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l_songs',
            name='thumbnail',
        ),
    ]
